import {
  type Plugin,
  HierarchyPlugin,
  DefaultRendererPlugin,
  TransformPlugin,
  CanvasPlugin,
  CameraPlugin,
  EventPlugin,
  ScreenshotPlugin,
  PenPlugin,
  CullingPlugin,
  HTMLPlugin,
  AnimationPlugin,
} from './plugins';

export * from './API';
export * from './App';
export * from './commands';
export * from './components';
export * from './plugins';
export * from './animation';
export * from './systems';
export * from './environment';
export * from './context';
export {
  safeAddComponent,
  safeRemoveComponent,
} from './history';
export {
  svgSvgElementToComputedCamera,
  svgElementsToSerializedNodes,
  serializedNodesToEntities,
  serializeNodesToSVGElements,
  applySvgDataAttributesToElement,
  imageToCanvas,
  randomInteger,
  isGradient,
  isPattern,
  isDataUrl,
  isUrl,
  isBrowser,
  formatNumber,
  parseGradient,
  isMeshGradientGradient,
  effectiveMeshGradientPointsNum,
  computeLinearGradient,
  computeRadialGradient,
  computeConicGradient,
  parseEffect,
  formatFilter,
  filterStringUsesEngineTimeCrt,
  filterStringUsesEngineTimePost,
  filterStringUsesEngineTimeGlitch,
  ADJUSTMENT_DEFAULTS,
  parseColor,
  cssColorToHex,
  serializePoints,
  deserializePoints,
  createSVGElement,
  exportFillGradientOrPattern,
  exportFillImage,
  exportMarker,
  toSVG,
  toSVGDataURL,
  toDomPrecision,
  loadBitmapFont,
  parseClipboard,
  cloneSerializedNodes,
  createPasteEvent,
  readSystemClipboard,
  isSupportedImageFileType,
  inferXYWidthHeight,
  applyPathPreserveLayoutFromSnapshot,
  inferPointsWithFromIdAndToId,
  inferEdgePoints,
  edgeEndsResolvable,
  hasTerminalPoint,
  layoutTextAnchoredInParent,
  pointAlongPolylineByT,
  getSvgPathFromStroke,
  distanceBetweenPoints,
  filterUndefined,
  isSaturateOnlyAdjustment,
  FLUTED_GLASS_DEFAULTS,
  CRT_DEFAULTS,
  VIGNETTE_DEFAULTS,
  vignetteUniformValues,
  ASCII_DEFAULTS,
  asciiUniformValues,
  GLITCH_DEFAULTS,
  glitchUniformValues,
  LIQUID_GLASS_DEFAULTS,
  liquidGlassUniformValues,
  LIQUID_METAL_DEFAULTS,
  liquidMetalUniformValues,
  TSUNAMI_DEFAULTS,
  tsunamiUniformValues,
  BURN_DEFAULTS,
  burnUniformValues,
  DIRECTION_EAST,
  DIRECTION_NORTH,
  DIRECTION_SOUTH,
  DIRECTION_WEST,
  MIME_TYPES,
  IMAGE_MIME_TYPES,
  EdgeStyle,
  type Gradient,
  type MeshGradient,
  formatMeshGradientStringSuffix,
  DEFAULT_MESH_GRADIENT_CORNER_POSITIONS,
  type Effect,
  type FlutedGlassEffect,
  type TsunamiEffect,
  type BurnEffect,
  type CrtEffect,
  type VignetteEffect,
  type AsciiEffect,
  type GlitchEffect,
  type LiquidGlassEffect,
  type LiquidMetalEffect,
} from './utils';
export * from './utils/design-variables';
export * from './utils/entity-design-bindings';
export * from './types/serialized-node';
export type { EdgeState } from './utils/binding/connection';
export { TexturePool } from './resources';

export {
  co,
  component,
  system,
  field,
  Type,
  World,
  System,
  type ComponentType,
  type Entity,
} from '@lastolivegames/becsy';

export { type IPointData } from '@pixi/math';

export const DefaultPlugins: Plugin[] = [
  HierarchyPlugin,
  TransformPlugin,
  CanvasPlugin,
  CameraPlugin,
  EventPlugin,
  CullingPlugin,
  DefaultRendererPlugin,
  ScreenshotPlugin,
  PenPlugin,
  HTMLPlugin,
  AnimationPlugin,
];
