import {
  type Plugin,
  HierarchyPlugin,
  DefaultRendererPlugin,
  TransformPlugin,
  CanvasPlugin,
  CameraPlugin,
  EventPlugin,
  ScreenshotPlugin,
  PenPlugin,
  CullingPlugin,
  HTMLPlugin,
  AnimationPlugin,
} from './plugins';

export * from './API';
export * from './format/ic-document';
export * from './App';
export * from './commands';
export * from './components';
export * from './plugins';
export * from './animation';
export * from './systems';
export * from './environment';
export * from './context';
export {
  safeAddComponent,
  safeRemoveComponent,
} from './history';
export {
  svgSvgElementToComputedCamera,
  svgElementsToSerializedNodes,
  serializedNodesToEntities,
  serializeNodesToSVGElements,
  applySvgDataAttributesToElement,
  imageToCanvas,
  randomInteger,
  isGradient,
  isPattern,
  isDataUrl,
  isUrl,
  isBrowser,
  formatNumber,
  parseGradient,
  isMeshGradientGradient,
  effectiveMeshGradientPointsNum,
  computeLinearGradient,
  computeRadialGradient,
  computeConicGradient,
  parseEffect,
  formatFilter,
  createDefaultEffect,
  formatLutFilterSegment,
  filterStringUsesEngineTimeCrt,
  filterStringUsesEngineTimePost,
  filterStringUsesEngineTimeGlitch,
  ADJUSTMENT_DEFAULTS,
  SATURATE_ADJUSTMENT_SATURATION,
  HALFTONE_DOTS_DEFAULTS,
  BLUR_DEFAULTS,
  LUT_EFFECT_DEFAULTS,
  parseColor,
  cssColorToHex,
  serializePoints,
  deserializePoints,
  createSVGElement,
  exportFillGradientOrPattern,
  exportStrokeGradientOrPattern,
  exportFillImage,
  rasterizeFillLayerImageUrlForTexture,
  resolveFillLayerImageRasterPixelSize,
  getFillLayerDecodedBitmap,
  setFillLayerDecodedBitmapForUrl,
  fillLayerImageRasterOptions,
  resolveFillLayerOpacityFromWire,
  resolveImageFillRasterOptions,
  computeObjectFitDrawRect,
  drawCanvasImageWithObjectFit,
  parseObjectPosition,
  exportMarker,
  toSVG,
  toSVGDataURL,
  toDomPrecision,
  loadBitmapFont,
  parseClipboard,
  cloneSerializedNodes,
  createPasteEvent,
  readSystemClipboard,
  isSupportedImageFileType,
  inferXYWidthHeight,
  applyPathPreserveLayoutFromSnapshot,
  inferPointsWithFromIdAndToId,
  inferEdgePoints,
  edgeEndsResolvable,
  hasTerminalPoint,
  layoutTextAnchoredInParent,
  pointAlongPolylineByT,
  getSvgPathFromStroke,
  distanceBetweenPoints,
  filterUndefined,
  isSaturateOnlyAdjustment,
  FLUTED_GLASS_DEFAULTS,
  CRT_DEFAULTS,
  VIGNETTE_DEFAULTS,
  vignetteUniformValues,
  ASCII_DEFAULTS,
  asciiUniformValues,
  GLITCH_DEFAULTS,
  glitchUniformValues,
  LIQUID_GLASS_DEFAULTS,
  liquidGlassUniformValues,
  LIQUID_METAL_DEFAULTS,
  LIQUID_METAL_POISSON_DEFAULTS,
  liquidMetalUniformValues,
  imageDataToLiquidMetalPoissonMap,
  isLiquidMetalReadbackSyncSupported,
  HEATMAP_DEFAULTS,
  heatmapUniformValues,
  imageDataToHeatmapProcessed,
  GEM_SMOKE_DEFAULTS,
  gemSmokeUniformValues,
  TSUNAMI_DEFAULTS,
  tsunamiUniformValues,
  RAIN_DEFAULTS,
  RAIN_DROP_TEXTURE_DEFAULTS,
  createDefaultRainEffect,
  RAIN_DROPDROP_TEXTURE_DEFAULT,
  RAINDROP_FX_RENDER_DEFAULTS,
  RAINDROP_FX_COMPOSE_DEFAULTS,
  RAINDROP_FX_COMPOSE_DECAY_DEFAULT,
  RAINDROP_FX_SIM_DEFAULTS,
  RAINDROP_FX_SIM_DT,
  RAINDROPS_WATER_DEFAULTS,
  RAINDROPS_SIM_DEFAULTS,
  rainUniformValues,
  rainCodropsWaterUniformValues,
  raindropsSimulatorOptionsForEffect,
  raindropSimulatorOptionsForEffect,
  rainFxRenderOptionsFromEffect,
  isRainFxEffect,
  isRainCodropsRainEffect,
  RaindropsCodropsSimulator,
  BURN_DEFAULTS,
  burnUniformValues,
  DIRECTION_EAST,
  DIRECTION_NORTH,
  DIRECTION_SOUTH,
  DIRECTION_WEST,
  MIME_TYPES,
  IMAGE_MIME_TYPES,
  EdgeStyle,
  type Gradient,
  type MeshGradient,
  formatMeshGradientStringSuffix,
  DEFAULT_MESH_GRADIENT_CORNER_POSITIONS,
  type Effect,
  type DefaultEffectKind,
  type HalftoneDotsEffect,
  type FlutedGlassEffect,
  type TsunamiEffect,
  type RainEffect,
  type RainCodropsWaterParams,
  type RainCodropsSimParams,
  type RainFxParams,
  type RainFxSimParams,
  type RaindropFxBackgroundWrapMode,
  type BurnEffect,
  type BlurEffect,
  type CrtEffect,
  type VignetteEffect,
  type AsciiEffect,
  type GlitchEffect,
  type LiquidGlassEffect,
  type LiquidMetalEffect,
  type HeatmapEffect,
  type GemSmokeEffect,
  type LutEffect,
  registerCubeLutFromText,
  listRegisteredCubeLutKeys,
  parseAdobeCube,
} from './utils';
export {
  serializedNodesToCode,
  buildCodeIR,
  emitReactTailwind,
  emitHtmlCss,
  type CodeFramework,
  type CodeVariablesMode,
  type CodeComponentStructure,
  type CodegenOptions,
  type CodeIR,
  type CodeNode,
  type CodeComponentDef,
  type StyleIR,
  type StyleValue,
} from './utils/codegen';
export * from './utils/icon-font';
export * from './utils/group-presentation';
export * from './utils/normalize-fill-wire';
export * from './utils/normalize-stroke-wire';
export * from './utils/design-variables';
export * from './utils/entity-design-bindings';
export * from './types/serialized-node';
export * from './types/fill-layer-blend';
export * from './filter';
export type { EdgeState } from './utils/binding/connection';
export { TexturePool } from './resources';

export {
  co,
  component,
  system,
  field,
  Type,
  World,
  System,
  type ComponentType,
  type Entity,
} from '@lastolivegames/becsy';

export { type IPointData } from '@pixi/math';

export const DefaultPlugins: Plugin[] = [
  HierarchyPlugin,
  TransformPlugin,
  CanvasPlugin,
  CameraPlugin,
  EventPlugin,
  CullingPlugin,
  DefaultRendererPlugin,
  ScreenshotPlugin,
  PenPlugin,
  HTMLPlugin,
  AnimationPlugin,
];
