/**
 * Filter effect types — source of truth: `packages/plugin-filter`.
 * Uses standalone `effect-types.d.ts` so `tsc` does not compile plugin-filter into `ecs` output.
 */
export type {
  Effect,
  DefaultEffectKind,
  FilterObject,
  AdjustmentEffect,
  BrightnessEffect,
  ContrastEffect,
  HueSaturationEffect,
  PixelateEffect,
  DotEffect,
  ColorHalftoneEffect,
  HalftoneDotsEffect,
  FlutedGlassEffect,
  TsunamiEffect,
  RainEffect,
  BurnEffect,
  CrtEffect,
  VignetteEffect,
  AsciiEffect,
  GlitchEffect,
  LiquidGlassEffect,
  LiquidMetalEffect,
  HeatmapEffect,
  GemSmokeEffect,
  LutEffect,
  DropShadowEffect,
  BlurEffect,
  NoiseEffect,
  FXAA,
  RainFxParams,
  RainFxSimParams,
  RainCodropsWaterParams,
  RainCodropsSimParams,
  RaindropsCodropsSimOptions,
  RainFxRenderOptions,
  RaindropFxBackgroundWrapMode,
  RaindropFxComposeMode,
} from '@infinite-canvas-tutorial/plugin-filter/effect-types';
